8391256: TestZoneTextPrinterParser.java assertion fails with expected: <Mountain Standard Time> but was: <Mountain Daylight Time>
(cherry picked from commit 131ab7478447cbfafccb320980b733763d4abe6d)